import type { Metadata } from "next";
import { IBM_Plex_Mono,Inter } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400","500","600","700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${plexMono.variable} antialiased`}
      >
		{/* Themes dark/light */}
		<ThemeProvider attribute="class" 
		defaultTheme="dark"
		enableSystem
		disableTransitionOnChange>

			{children}
		</ThemeProvider>
        
      </body>
    </html>
  );
}
