import type { Metadata } from "next";
import {
	ClerkProvider,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
	UserButton,
} from '@clerk/nextjs'
import {  IBM_Plex_Mono, Inter } from "next/font/google";
import { dark } from "@clerk/themes"
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});


const plexMono = IBM_Plex_Mono({
	variable: "--font-plex-mono",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider appearance={
			{ theme: dark }
		}>
			<html lang="en" suppressHydrationWarning>
				<body
					className={`${inter.variable} ${plexMono.variable} antialiased`}
				>
					{/* Themes dark/light */}
					<ThemeProvider attribute="class"
						defaultTheme="dark"
						enableSystem
						disableTransitionOnChange>
						<header>
							<SignedOut>
								<SignInButton />

								<SignUpButton>
									<button className="bg-rose-500 text-white p-2">
										Sign Up
									</button>
								</SignUpButton>
							</SignedOut>
							<SignedIn>
								<UserButton />
							</SignedIn>
						</header>
						{children}
					</ThemeProvider>

				</body>
			</html>
		</ClerkProvider >

	);
}
